series: GLFW Graphics
title: Obj Loading
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: This program demonstrates loading of obj model files to render them in a scene.
language: C++
tags:
  - Graphics
extra_resources:
  - title: OpenGL reference for Uniform Buffer Object
    link: "https://www.opengl.org/wiki/Uniform_Buffer_Object"
connections:
  - series: GLFW Graphics
    title: Multi-Object Multi-Buffer
